/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto3semestre;

import java.awt.Image;
import java.sql.Connection;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Diaz
 */
public class Login extends javax.swing.JFrame {
    
    Connection connection;
    ConexionBaseDeDatos conector;
    int intentos=0;

    /**
     * Creates new form Login
     */
    public Login() {
        conector= new ConexionBaseDeDatos();
        connection= conector.crearConeccion();
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        loginBoton = new javax.swing.JButton();
        contrasena = new javax.swing.JTextField();
        logoUsuario = new javax.swing.JLabel();
        logoContraseña = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3semestre/images/Despegando (5).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 127, -1));

        loginBoton.setText("Iniciar");
        loginBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBotonMouseClicked(evt);
            }
        });
        loginBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBotonActionPerformed(evt);
            }
        });
        getContentPane().add(loginBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        contrasena.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 12)); // NOI18N
        getContentPane().add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 127, -1));

        logoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3semestre/images/usuario.png"))); // NOI18N
        getContentPane().add(logoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 170, -1, 40));

        logoContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3semestre/images/Contraseña.png"))); // NOI18N
        getContentPane().add(logoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3semestre/images/Despegando (5).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 60, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto3semestre/images/logo2..png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
 
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void loginBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBotonMouseClicked
         Usuario usuario = conector.buscarUsuario(nombreUsuario.getText(), connection);
         
        if(usuario != null && contrasena.getText().equals(usuario.getContrasena())){
            if(usuario.getRol().equals("SuperAdmin")){
                MenuSuperAdmin menuSuperAdmin = new MenuSuperAdmin();
                menuSuperAdmin.setUsuarioSesion(usuario);
                menuSuperAdmin.show();
                this.dispose();
            }else if(usuario.getRol().equals("Admin")){
                MenuAdmin menuAdmin = new MenuAdmin();
                menuAdmin.setUsuarioSesion(usuario);
                menuAdmin.show();
                this.dispose();
            }else if(usuario.getRol().equals("Usuario")){
                MenuUsuario menuUsuario = new MenuUsuario();
                menuUsuario.setUsuarioSesion(usuario);
                menuUsuario.show();
                this.dispose();
            }
        }else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            intentos++;
            
            if (intentos==3) {
                
                this.dispose();
            }
        }
    }//GEN-LAST:event_loginBotonMouseClicked

    private void loginBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBoton;
    private javax.swing.JLabel logoContraseña;
    private javax.swing.JLabel logoUsuario;
    private javax.swing.JTextField nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
